image: maven:3.5.0-jdk-8

cache:
  paths:
    - maven.repository/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  HOST: "pieckcraft.nl"
  USERNAME: "admin"
  PASSWORD: "michel00"
  TARGET: "/"

compile:
  stage: build
  script:
    - mvn install
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev /builds/Eftelist/PieckRides/builds/ $TARGET --parallel=10"

verify:
  script:
    - mvn verify